name: Build Auth

on:
  release:
    types: [ published ]

env:
  AWS_REGION : "eu-west-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build_jwt_validator:
    name: Build JWT Validator
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build ./cmd/jwt-validator-lambda

      - name: Zip
        run: zip jwt-validator-${{ steps.get_version.outputs.VERSION }}.zip jwt-validator

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: put object S3
        run: aws s3 cp ./jwt-validator-${{ steps.get_version.outputs.VERSION }}.zip s3://tiborhercz-github-release-assets/dummynotes/
