name: Build Auth

on: push
#  release:
#    types: [ published ]

jobs:
  build_jwt_validator:
    name: Build JWT Validator
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build ./cmd/jwt-validator

      - name: Zip
        run: zip jwt-validator.zip jwt-validator
